name: Pipeline Failure Notification

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      # ✓ Requirement 4: Email notification on failure
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: CI/CD Pipeline Failed
          body: The CI/CD pipeline has failed. Please check the GitHub Actions logs.
          to: ${{ github.event.workflow_run.head_commit.author.email }}
          from: CI/CD Pipeline 