name: Email Notification Workflow

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]  # Match the exact name from ci-cd.yml
    types: [completed]
    branches: [main]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp-mail.outlook.com  # Outlook SMTP server since you're using outlook.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: CI/CD Pipeline Failed
          body: The CI/CD pipeline has failed. Please check the GitHub Actions logs.
          to: henriqueos98@outlook.com
          from: CI/CD Pipeline <${{ secrets.EMAIL_USERNAME }}>
          secure: true 